controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# Redireccionar ra√≠z a login
index:
    path: /hola
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        route: 'app_login'
        permanent: false
